#include <pch.h>
#include "../TextureEncoding.h"

#include <bc7enc_rdo/bc7e_ispc.h> // BC7 (generated by the custom build step)

EncodeResult EncodeWithBc7e(const ImageView& image, const EncodeParams& params, std::span<std::byte> out)
{
    static const bool initialized = (ispc::bc7e_compress_block_init(), true);   // runs once, thread-safe
    (void)initialized;

    if (image.hdr)
        return std::unexpected("bc7e needs RGBA8 input");

    ispc::bc7e_compress_block_params settings;
    const bool perceptual = GetFormatInfo(params.format).srgb;
    switch (params.quality)
    {
    case EncodeQuality::Fast:   ispc::bc7e_compress_block_params_init_veryfast(&settings, perceptual); break;
    case EncodeQuality::Normal: ispc::bc7e_compress_block_params_init_basic(&settings, perceptual);    break;
    case EncodeQuality::Best:   ispc::bc7e_compress_block_params_init_slow(&settings, perceptual);     break;
    }

    const uint32_t blocksX = (image.width + 3) / 4;
    const uint32_t blocksY = (image.height + 3) / 4;

    std::vector<std::byte> row(size_t(blocksX) * 64);   // one row of blocks, 16 RGBA8 pixels each
    for (uint32_t by = 0; by < blocksY; ++by)
    {
        for (uint32_t bx = 0; bx < blocksX; ++bx)
            GatherBlockRGBA8(image, bx, by, 4, 4, std::span(row).subspan(size_t(bx) * 64, 64));

        auto* dst = reinterpret_cast<uint64_t*>(out.data() + size_t(by) * blocksX * 16);
        ispc::bc7e_compress_blocks(blocksX, dst, reinterpret_cast<const uint32_t*>(row.data()), &settings);
    }
    return {};
}