#version 460
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D inMips[];
layout(set = 0, binding = 1, rgba16f) uniform image2D outMips[];

layout(push_constant) uniform PushConstants {
    vec2 invInputSize;
    uint inputIdx;
    uint outputIdx;
} pc;

void main()
{
    ivec2 writeCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputSize = imageSize(outMips[pc.outputIdx]);
    
    if (writeCoord.x >= outputSize.x || writeCoord.y >= outputSize.y) return;

    vec2 uv = (vec2(writeCoord) + vec2(0.5)) * (1.0 / vec2(outputSize));
    float x = pc.invInputSize.x;
    float y = pc.invInputSize.y;

    // Jorge Jimenez 13-tap filter
    vec3 a = texture(inMips[pc.inputIdx], vec2(uv.x - 2.0*x, uv.y + 2.0*y)).rgb;
    vec3 b = texture(inMips[pc.inputIdx], vec2(uv.x,         uv.y + 2.0*y)).rgb;
    vec3 c = texture(inMips[pc.inputIdx], vec2(uv.x + 2.0*x, uv.y + 2.0*y)).rgb;

    vec3 d = texture(inMips[pc.inputIdx], vec2(uv.x - 1.0*x, uv.y + 1.0*y)).rgb;
    vec3 e = texture(inMips[pc.inputIdx], vec2(uv.x + 1.0*x, uv.y + 1.0*y)).rgb;

    vec3 f = texture(inMips[pc.inputIdx], vec2(uv.x - 2.0*x, uv.y)).rgb;
    vec3 g = texture(inMips[pc.inputIdx], vec2(uv.x,         uv.y)).rgb;
    vec3 h = texture(inMips[pc.inputIdx], vec2(uv.x + 2.0*x, uv.y)).rgb;

    vec3 i = texture(inMips[pc.inputIdx], vec2(uv.x - 1.0*x, uv.y - 1.0*y)).rgb;
    vec3 j = texture(inMips[pc.inputIdx], vec2(uv.x + 1.0*x, uv.y - 1.0*y)).rgb;

    vec3 k = texture(inMips[pc.inputIdx], vec2(uv.x - 2.0*x, uv.y - 2.0*y)).rgb;
    vec3 l = texture(inMips[pc.inputIdx], vec2(uv.x,         uv.y - 2.0*y)).rgb;
    vec3 m = texture(inMips[pc.inputIdx], vec2(uv.x + 2.0*x, uv.y - 2.0*y)).rgb;

    vec3 color = e * 0.125;
    color += (a+c+g+k+m) * 0.03125;
    color += (b+d+f+h+i+j+l) * 0.0625;

    // Apply Karis average on the very first downsample to prevent fireflies
    if (pc.inputIdx == 0) {
        float luma = dot(color, vec3(0.2126, 0.7152, 0.0722));
        color *= (1.0 / (1.0 + luma));
    }

    imageStore(outMips[pc.outputIdx], writeCoord, vec4(color, 1.0));
}